USE krautundrueben; -- Select DB: krautundrueben

/* ------------------- Allergene ------------------- */
-- insert Allergen i.e. Gluten...

INSERT INTO ALLERGENE (ALLERGEN) VALUES ("Laktose");
INSERT INTO ALLERGENE (ALLERGEN) VALUES ("Weizen");
INSERT INTO ALLERGENE (ALLERGEN) VALUES ("Gluten");
INSERT INTO ALLERGENE (ALLERGEN) VALUES ("Stärke");
INSERT INTO ALLERGENE (ALLERGEN) VALUES ("Karotte");

/* ------------------- ERNAHRUNGSKATEGORIEN ------------------- */
-- insert Kategorien i.e. Veagn...

INSERT INTO ERNAHRUNGSKATEGORIEN (KATEGORIE, BESCHREIBUNG) VALUES ("Vegan", "Darf keine tierischen Produkte enthalten.");
INSERT INTO ERNAHRUNGSKATEGORIEN (KATEGORIE, BESCHREIBUNG) VALUES ("Vegatarisch", "Darf kein Fleisch enthalten.");
INSERT INTO ERNAHRUNGSKATEGORIEN (KATEGORIE, BESCHREIBUNG) VALUES ("Frutarisch", "Vegetarische Ernährungsweise die auf Früchten basiert.");
INSERT INTO ERNAHRUNGSKATEGORIEN (KATEGORIE, BESCHREIBUNG) VALUES ("ohne Gentechnik", "Darf keine Gentechnisch modifizierten Lebensmittel enthalten.");
INSERT INTO ERNAHRUNGSKATEGORIEN (KATEGORIE, BESCHREIBUNG) VALUES ("Laktosefrei", "Darf keine Milchprodukte enthalten.");
INSERT INTO ERNAHRUNGSKATEGORIEN (KATEGORIE, BESCHREIBUNG) VALUES ("Glutenfrei", "Darf kein Gluten enthalten.");
INSERT INTO ERNAHRUNGSKATEGORIEN (KATEGORIE, BESCHREIBUNG) VALUES ("Low Carb", "Kohlenhydrate minimierte ernährungsweise.");

/* ------------------- Neue Zutaten ------------------- */
-- insert additional Zutaten that are required for certan Rezepte

INSERT INTO ZUTAT (ZUTATENNR, BEZEICHNUNG, EINHEIT, NETTOPREIS, BESTAND, lieferant, KALORIEN, KOHLENHYDRATE, PROTEIN) VALUES (9002, "Lasagneplatten", "Stück", 0.21, 500, 101, 23, 12, 2);
INSERT INTO ZUTAT (ZUTATENNR, BEZEICHNUNG, EINHEIT, NETTOPREIS, BESTAND, lieferant, KALORIEN, KOHLENHYDRATE, PROTEIN) VALUES (9003, "Spinat", "kilogramm", 0.45, 5, 102, 12, 5, 10);
INSERT INTO ZUTAT (ZUTATENNR, BEZEICHNUNG, EINHEIT, NETTOPREIS, BESTAND, lieferant, KALORIEN, KOHLENHYDRATE, PROTEIN) VALUES (9004, "Lachs", "kilogramm", 1.42, 2, 101, 45, 15, 20);
INSERT INTO ZUTAT (ZUTATENNR, BEZEICHNUNG, EINHEIT, NETTOPREIS, BESTAND, lieferant, KALORIEN, KOHLENHYDRATE, PROTEIN) VALUES (9005, "Käse", "kilogramm", 0.7, 1.5, 101, 250, 1, 3);
INSERT INTO ZUTAT (ZUTATENNR, BEZEICHNUNG, EINHEIT, NETTOPREIS, BESTAND, lieferant, KALORIEN, KOHLENHYDRATE, PROTEIN) VALUES (9006, "Mehl", "kilogramm", 0.23, 6, 101, 23, 3, 1);
INSERT INTO ZUTAT (ZUTATENNR, BEZEICHNUNG, EINHEIT, NETTOPREIS, BESTAND, lieferant, KALORIEN, KOHLENHYDRATE, PROTEIN) VALUES (9007, "Sahne", "Liter", 0.45, 1, 101, 120, 4, 3);
INSERT INTO ZUTAT (ZUTATENNR, BEZEICHNUNG, EINHEIT, NETTOPREIS, BESTAND, lieferant, KALORIEN, KOHLENHYDRATE, PROTEIN) VALUES (9008, "Parmesan", "gramm", 55, 0.5, 101, 121, 2.5, 3.1);
INSERT INTO ZUTAT (ZUTATENNR, BEZEICHNUNG, EINHEIT, NETTOPREIS, BESTAND, lieferant, KALORIEN, KOHLENHYDRATE, PROTEIN) VALUES (9009, "Zitrone", "Stück", 0.23, 200, 101, 24, 1.2, 0.7);
INSERT INTO ZUTAT (ZUTATENNR, BEZEICHNUNG, EINHEIT, NETTOPREIS, BESTAND, lieferant, KALORIEN, KOHLENHYDRATE, PROTEIN) VALUES (9010, "Pfeffer", "gramm", 0.21, 470, 101, 12, 0.3, 0.3);
INSERT INTO ZUTAT (ZUTATENNR, BEZEICHNUNG, EINHEIT, NETTOPREIS, BESTAND, lieferant, KALORIEN, KOHLENHYDRATE, PROTEIN) VALUES (9011, "Muskat", "gramm", 0.45, 400, 101, 17, 0.7, 0.4);
INSERT INTO ZUTAT (ZUTATENNR, BEZEICHNUNG, EINHEIT, NETTOPREIS, BESTAND, lieferant, KALORIEN, KOHLENHYDRATE, PROTEIN) VALUES (9012, "Hähnchenbrustfilet", "gramm", 0.76, 500, 101, 26, 12, 43);
INSERT INTO ZUTAT (ZUTATENNR, BEZEICHNUNG, EINHEIT, NETTOPREIS, BESTAND, lieferant, KALORIEN, KOHLENHYDRATE, PROTEIN) VALUES (9013, "Reis", "kilogramm", 0.12, 15, 101, 56, 14, 3);
INSERT INTO ZUTAT (ZUTATENNR, BEZEICHNUNG, EINHEIT, NETTOPREIS, BESTAND, lieferant, KALORIEN, KOHLENHYDRATE, PROTEIN) VALUES (9014, "Sojasauce", "Liter", 0.42, 1, 101, 34, 1, 2);
INSERT INTO ZUTAT (ZUTATENNR, BEZEICHNUNG, EINHEIT, NETTOPREIS, BESTAND, lieferant, KALORIEN, KOHLENHYDRATE, PROTEIN) VALUES (9015, "Zucker", "kilogramm", 0.41, 3, 101, 142, 0.1, 0.2);
INSERT INTO ZUTAT (ZUTATENNR, BEZEICHNUNG, EINHEIT, NETTOPREIS, BESTAND, lieferant, KALORIEN, KOHLENHYDRATE, PROTEIN) VALUES (9016, "Bambussprossen", "Stück", 0.21, 200, 101, 45, 3, 5);
INSERT INTO ZUTAT (ZUTATENNR, BEZEICHNUNG, EINHEIT, NETTOPREIS, BESTAND, lieferant, KALORIEN, KOHLENHYDRATE, PROTEIN) VALUES (9017, "Kokosmilch", "Liter", 0.24, 1, 101, 34, 12, 15);
INSERT INTO ZUTAT (ZUTATENNR, BEZEICHNUNG, EINHEIT, NETTOPREIS, BESTAND, lieferant, KALORIEN, KOHLENHYDRATE, PROTEIN) VALUES (9018, "Currypaste", "gramm", 0.65, 500, 101, 23, 4, 3);
INSERT INTO ZUTAT (ZUTATENNR, BEZEICHNUNG, EINHEIT, NETTOPREIS, BESTAND, lieferant, KALORIEN, KOHLENHYDRATE, PROTEIN) VALUES (9019, "Petersilie", "Bund", 0.32, 15, 101, 12, 1, 1);
INSERT INTO ZUTAT (ZUTATENNR, BEZEICHNUNG, EINHEIT, NETTOPREIS, BESTAND, lieferant, KALORIEN, KOHLENHYDRATE, PROTEIN) VALUES (9020, "Majoran", "gramm", 0.22, 500, 101, 5, 0.41, 0.2);
INSERT INTO ZUTAT (ZUTATENNR, BEZEICHNUNG, EINHEIT, NETTOPREIS, BESTAND, lieferant, KALORIEN, KOHLENHYDRATE, PROTEIN) VALUES (9021, "Milchreis", "kilogramm", 1.3, 4, 101, 67, 2, 3);
INSERT INTO ZUTAT (ZUTATENNR, BEZEICHNUNG, EINHEIT, NETTOPREIS, BESTAND, lieferant, KALORIEN, KOHLENHYDRATE, PROTEIN) VALUES (9022, "Vanillezucker", "gramm", 0.76, 400, 101, 87, 0.4, 0.3);
INSERT INTO ZUTAT (ZUTATENNR, BEZEICHNUNG, EINHEIT, NETTOPREIS, BESTAND, lieferant, KALORIEN, KOHLENHYDRATE, PROTEIN) VALUES (9023, "Apfelmus", "gramm", 0.96, 450, 101, 45, 2.4, 1.3);
INSERT INTO ZUTAT (ZUTATENNR, BEZEICHNUNG, EINHEIT, NETTOPREIS, BESTAND, lieferant, KALORIEN, KOHLENHYDRATE, PROTEIN) VALUES (9024, "Oregano", "gramm", 0.32, 130, 101, 23, 2.6, 3.3);
INSERT INTO ZUTAT (ZUTATENNR, BEZEICHNUNG, EINHEIT, NETTOPREIS, BESTAND, lieferant, KALORIEN, KOHLENHYDRATE, PROTEIN) VALUES (9025, "Pflanzenöl", "Liter", 0.42, 5, 101, 76, 6.6, 3);
INSERT INTO ZUTAT (ZUTATENNR, BEZEICHNUNG, EINHEIT, NETTOPREIS, BESTAND, lieferant, KALORIEN, KOHLENHYDRATE, PROTEIN) VALUES (9026, "Salz", "kilogramm", 0.1, 5, 101, 3, 0, 0);
INSERT INTO ZUTAT (ZUTATENNR, BEZEICHNUNG, EINHEIT, NETTOPREIS, BESTAND, lieferant, KALORIEN, KOHLENHYDRATE, PROTEIN) VALUES (9027, "Paprikaschote", "Stück", 0.34, 200, 101, 45, 2, 0.7);
