USE krautundrueben;

SELECT REZEPTE.REZEPTNR, REZEPTE.REZEPT, COUNT(REZEPTZUTATEN.ZUTATENNR) AS "Zutatenanzahl", REZEPTKATEGORIEN.KATEGORIENR, ERNAHRUNGSKATEGORIEN.KATEGORIE
FROM REZEPTE
JOIN REZEPTZUTATEN ON REZEPTE.REZEPTNR = REZEPTZUTATEN.REZEPTNR
JOIN REZEPTKATEGORIEN ON REZEPTE.REZEPTNR = REZEPTKATEGORIEN.REZEPTNR
NATURAL JOIN ERNAHRUNGSKATEGORIEN

WHERE REZEPTKATEGORIEN.KATEGORIENR = 2

GROUP BY REZEPTZUTATEN.REZEPTNR

HAVING COUNT(REZEPTZUTATEN.ZUTATENNR) < 5 ;
