USE krautundrueben;

SELECT ZUTAT.ZUTATENNR, ZUTAT.BEZEICHNUNG, REZEPTZUTATEN.MENGE, REZEPTZUTATEN.EINHEIT
FROM(( ZUTAT

INNER JOIN REZEPTZUTATEN ON ZUTAT.ZUTATENNR        = REZEPTZUTATEN.ZUTATENNR )
INNER JOIN REZEPTE       ON REZEPTZUTATEN.REZEPTNR = REZEPTE.REZEPTNR        )

WHERE REZEPT = "Lachslasagne";
