USE krautundrueben;

SELECT REZEPTKATEGORIEN.REZEPTNR, REZEPTE.REZEPT, REZEPTKATEGORIEN.KATEGORIENR, ERNAHRUNGSKATEGORIEN.KATEGORIE
FROM(( REZEPTE

LEFT  JOIN REZEPTKATEGORIEN     ON REZEPTE.REZEPTNR             = REZEPTKATEGORIEN.REZEPTNR        )
RIGHT JOIN ERNAHRUNGSKATEGORIEN ON REZEPTKATEGORIEN.KATEGORIENR = ERNAHRUNGSKATEGORIEN.KATEGORIENR )

WHERE KATEGORIE = "Vegan";
