USE krautundrueben;

SELECT REZEPTZUTATEN.REZEPTNR, REZEPTE.REZEPT, REZEPTZUTATEN.ZUTATENNR, ZUTAT.BEZEICHNUNG, REZEPTZUTATEN.MENGE, REZEPTZUTATEN.EINHEIT
FROM(( REZEPTE

INNER JOIN REZEPTZUTATEN ON REZEPTE.REZEPTNR        = REZEPTZUTATEN.REZEPTNR )
INNER JOIN ZUTAT         ON REZEPTZUTATEN.ZUTATENNR = ZUTAT.ZUTATENNR        )

WHERE BEZEICHNUNG = "Pfeffer";
