USE krautundrueben;

SELECT KUNDE.KUNDENNR,
       KUNDE.NACHNAME,
       ROUND(AVG(ZUTAT.KALORIEN),1) AS "Ø Kalorien",
       ROUND(AVG(ZUTAT.KOHLENHYDRATE),1) AS "Ø Kohlenhydrate",
       ROUND(AVG(ZUTAT.PROTEIN),1) AS "Ø Protein"

FROM BESTELLUNG
NATURAL JOIN BESTELLUNGZUTAT
NATURAL JOIN ZUTAT
NATURAL JOIN KUNDE

WHERE KUNDENNR = 2007;
