USE krautundrueben;

SELECT REZEPTE.REZEPTNR, REZEPTE.REZEPT, SUM(ZUTAT.KALORIEN) AS "Kalorien"
FROM REZEPTE

JOIN REZEPTZUTATEN ON REZEPTE.REZEPTNR = REZEPTZUTATEN.REZEPTNR
JOIN ZUTAT ON ZUTAT.ZUTATENNR = REZEPTZUTATEN.ZUTATENNR
GROUP BY REZEPTE.REZEPTNR

HAVING SUM(ZUTAT.KALORIEN) < 550;
