USE krautundrueben;

SELECT REZEPTE.REZEPTNR, REZEPTE.REZEPT, COUNT(REZEPTZUTATEN.ZUTATENNR) AS "Zutatenanzahl"
FROM REZEPTE

JOIN REZEPTZUTATEN ON REZEPTE.REZEPTNR = REZEPTZUTATEN.REZEPTNR
GROUP BY REZEPTZUTATEN.REZEPTNR

HAVING Zutatenanzahl < 5;
