USE krautundrueben;

SELECT ROUND(AVG(ZUTAT.KALORIEN)) AS "Ø Kalorien",
       ROUND(AVG(ZUTAT.KOHLENHYDRATE)) AS "Ø Kohlenhydrate",
       ROUND(AVG(ZUTAT.PROTEIN)) AS "Ø Protein"

FROM BESTELLUNG
NATURAL JOIN BESTELLUNGZUTAT
NATURAL JOIN ZUTAT

WHERE KUNDENNR = 2007
